# Copyright (c) 2019, UK HealthCare (https://ukhealthcare.uky.edu) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-html-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: wordpress-html-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - name: frontend
    protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
  
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: 127.0.0.1:30500/internal/wordpress:5.2.2-php7.3-apache-v1
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-secret
              key: password
        - name: WORDPRESS_CONFIG_EXTRA
          value: "define('WP_ALLOW_MULTISITE', true );"
        ports:
        - containerPort: 80
          name: wordpress
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 3 
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /wp-login.php
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
#wordpress-volume#        - name: wordpress-html-volume
#wordpress-volume#          mountPath: /var/www/html
#wordpress-volume#      volumes:
#wordpress-volume#      - name: wordpress-html-volume
#wordpress-volume#        persistentVolumeClaim:
#wordpress-volume#          claimName: wordpress-html-pv-claim
