apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: wordpress-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - name: frontend
    protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
  
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: 127.0.0.1:30500/internal/wordpress:5.2.2-php7.3-apache-v1
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-secret
              key: password
        - name: WORDPRESS_CONFIG_EXTRA
          value: "define('WP_ALLOW_MULTISITE', true );"
        ports:
        - containerPort: 80
          name: wordpress
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 3 
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /wp-login.php
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: wordpress-volume
          mountPath: /var/www/html
      volumes:
      - name: wordpress-volume
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
